/* Automatically generated by wasm2c, then trimmed. */
#ifndef CONTROL_FLOW_H_GENERATED_
#define CONTROL_FLOW_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint32_t u32;
typedef int32_t s32;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_control__flow {
  char dummy_member;
} w2c_control__flow;

void wasm2c_control__flow_instantiate(w2c_control__flow*);
void wasm2c_control__flow_free(w2c_control__flow*);

/* export: 'sum_to' */
u32 w2c_control__flow_sum_to(w2c_control__flow*, u32);

/* export: 'count_digits' */
u32 w2c_control__flow_count_digits(w2c_control__flow*, u32);

/* export: 'http_category' */
u32 w2c_control__flow_http_category(w2c_control__flow*, u32);

/* export: 'safe_div' */
u32 w2c_control__flow_safe_div(w2c_control__flow*, u32, u32);

/* export: 'must_be_small' */
u32 w2c_control__flow_must_be_small(w2c_control__flow*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* CONTROL_FLOW_H_GENERATED_ */
