/* Automatically generated by wasm2c, then trimmed. */
#include <assert.h>

#include "control_flow.h"

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#if WASM_RT_STACK_DEPTH_COUNT
#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION);

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth
#else
#define FUNC_PROLOGUE

#define FUNC_EPILOGUE
#endif

#define UNREACHABLE TRAP(UNREACHABLE)

#define DIV_S(ut, min, x, y)                                  \
  ((UNLIKELY((y) == 0))                  ? TRAP(DIV_BY_ZERO)  \
   : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
                                         : (ut)((x) / (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x)op(y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)

static u32 w2c_control__flow_f0(w2c_control__flow*, u32);
static u32 w2c_control__flow_f1(w2c_control__flow*, u32);
static u32 w2c_control__flow_f2(w2c_control__flow*, u32);
static u32 w2c_control__flow_f3(w2c_control__flow*, u32, u32);
static u32 w2c_control__flow_f4(w2c_control__flow*, u32);
static u32 w2c_control__flow_sum_to_0(w2c_control__flow*, u32);
static u32 w2c_control__flow_count_digits_0(w2c_control__flow*, u32);
static u32 w2c_control__flow_f7(w2c_control__flow*);
static u32 w2c_control__flow_f8(w2c_control__flow*);
static u32 w2c_control__flow_http_category_0(w2c_control__flow*, u32);
static u32 w2c_control__flow_safe_div_0(w2c_control__flow*, u32, u32);
static u32 w2c_control__flow_must_be_small_0(w2c_control__flow*, u32);

/* export: 'sum_to' */
u32 w2c_control__flow_sum_to(w2c_control__flow* instance, u32 var_p0) {
  u32 ret = w2c_control__flow_sum_to_0(instance, var_p0);
  return ret;
}

/* export: 'count_digits' */
u32 w2c_control__flow_count_digits(w2c_control__flow* instance, u32 var_p0) {
  u32 ret = w2c_control__flow_count_digits_0(instance, var_p0);
  return ret;
}

/* export: 'http_category' */
u32 w2c_control__flow_http_category(w2c_control__flow* instance, u32 var_p0) {
  u32 ret = w2c_control__flow_http_category_0(instance, var_p0);
  return ret;
}

/* export: 'safe_div' */
u32 w2c_control__flow_safe_div(w2c_control__flow* instance, u32 var_p0, u32 var_p1) {
  u32 ret = w2c_control__flow_safe_div_0(instance, var_p0, var_p1);
  return ret;
}

/* export: 'must_be_small' */
u32 w2c_control__flow_must_be_small(w2c_control__flow* instance, u32 var_p0) {
  u32 ret = w2c_control__flow_must_be_small_0(instance, var_p0);
  return ret;
}

void wasm2c_control__flow_instantiate(w2c_control__flow* instance) {
  assert(wasm_rt_is_initialized());
}

void wasm2c_control__flow_free(w2c_control__flow* instance) {
}

u32 w2c_control__flow_f0(w2c_control__flow* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_i1 = var_p0;
    var_i0 -= var_i1;
  } else {
    var_i0 = var_p0;
  }
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_f1(w2c_control__flow* instance, u32 var_p0) {
  u32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_l1 = var_i0;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_l1 = var_i0;
  }
  var_i0 = var_l1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_f2(w2c_control__flow* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 0u;
    var_i1 = var_p0;
    var_i0 -= var_i1;
  } else {
    var_i0 = var_p0;
  }
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_f3(w2c_control__flow* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i2 = var_p0;
  var_i3 = var_p1;
  var_i2 = (u32)((s32)var_i2 > (s32)var_i3);
  var_i0 = var_i2 ? var_i0 : var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_f4(w2c_control__flow* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 4294967295u;
    goto var_B0;
  }
  var_i0 = var_p0;
  var_i0 = !(var_i0);
  if (var_i0) {
    var_i0 = 0u;
    goto var_B0;
  }
  var_i0 = 1u;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_sum_to_0(w2c_control__flow* instance, u32 var_p0) {
  u32 var_l1 = 0, var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_L1: 
    var_i0 = var_l1;
    var_i1 = var_p0;
    var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
    if (var_i0) {goto var_B0;}
    var_i0 = var_l2;
    var_i1 = var_l1;
    var_i0 += var_i1;
    var_l2 = var_i0;
    var_i0 = var_l1;
    var_i1 = 1u;
    var_i0 += var_i1;
    var_l1 = var_i0;
    goto var_L1;
  var_B0:;
  var_i0 = var_l2;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_count_digits_0(w2c_control__flow* instance, u32 var_p0) {
  u32 var_l1 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = 1u;
  var_l1 = var_i0;
  var_i0 = var_p0;
  var_i1 = 10u;
  var_i0 = DIV_U(var_i0, var_i1);
  var_p0 = var_i0;
  var_L0: 
    var_i0 = var_p0;
    if (var_i0) {
      var_i0 = var_l1;
      var_i1 = 1u;
      var_i0 += var_i1;
      var_l1 = var_i0;
      var_i0 = var_p0;
      var_i1 = 10u;
      var_i0 = DIV_U(var_i0, var_i1);
      var_p0 = var_i0;
      goto var_L0;
    }
  var_i0 = var_l1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_f7(w2c_control__flow* instance) {
  u32 var_l0 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_L1: 
    var_L3: 
      var_i0 = var_l0;
      var_i1 = 50u;
      var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
      if (var_i0) {goto var_B0;}
      var_i0 = var_l0;
      var_i1 = 7u;
      var_i0 += var_i1;
      var_l0 = var_i0;
      goto var_L3;
    goto var_L1;
  var_B0:;
  var_i0 = var_l0;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_f8(w2c_control__flow* instance) {
  u32 var_l0 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_L1: 
    var_L3: 
      var_i0 = var_l0;
      var_i1 = 50u;
      var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
      if (var_i0) {goto var_B0;}
      var_i0 = var_l0;
      var_i1 = 7u;
      var_i0 += var_i1;
      var_l0 = var_i0;
      goto var_L3;
    goto var_L1;
  var_B0:;
  var_i0 = var_l0;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_http_category_0(w2c_control__flow* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 100u;
  var_i0 = DIV_U(var_i0, var_i1);
  switch (var_i0) {
    case 0: goto var_B0;
    case 1: goto var_B0;
    case 2: goto var_B4;
    case 3: goto var_B3;
    case 4: goto var_B2;
    case 5: goto var_B1;
    default: goto var_B0;
  }
  var_B4:;
  var_i0 = 200u;
  goto var_Bfunc;
  var_B3:;
  var_i0 = 300u;
  goto var_Bfunc;
  var_B2:;
  var_i0 = 400u;
  goto var_Bfunc;
  var_B1:;
  var_i0 = 500u;
  goto var_Bfunc;
  var_B0:;
  var_i0 = 0u;
  var_Bfunc:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_safe_div_0(w2c_control__flow* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p1;
  var_i0 = !(var_i0);
  if (var_i0) {
    var_i0 = 0u;
    goto var_Bfunc;
  }
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 = I32_DIV_S(var_i0, var_i1);
  var_Bfunc:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_control__flow_must_be_small_0(w2c_control__flow* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 100u;
  var_i0 = var_i0 > var_i1;
  if (var_i0) {
    UNREACHABLE;
  }
  var_i0 = var_p0;
  FUNC_EPILOGUE;
  return var_i0;
}
