/* Automatically generated by wasm2c, then trimmed */
#include <assert.h>
#include <math.h>
#include <string.h>

#if defined(_MSC_VER)
#include <intrin.h>
#endif

#include "basics.h"

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#if WASM_RT_STACK_DEPTH_COUNT
#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION);

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth
#else
#define FUNC_PROLOGUE

#define FUNC_EPILOGUE
#endif

#if defined(_MSC_VER)

// Adapted from
// https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h

static inline int I32_CLZ(unsigned long v) {
  unsigned long r = 0;
  if (_BitScanReverse(&r, v)) {
    return 31 - r;
  }
  return 32;
}

#define POPCOUNT_DEFINE_PORTABLE(f_n, T)                            \
  static inline u32 f_n(T x) {                                      \
    x = x - ((x >> 1) & (T) ~(T)0 / 3);                             \
    x = (x & (T) ~(T)0 / 15 * 3) + ((x >> 2) & (T) ~(T)0 / 15 * 3); \
    x = (x + (x >> 4)) & (T) ~(T)0 / 255 * 15;                      \
    return (T)(x * ((T) ~(T)0 / 255)) >> (sizeof(T) - 1) * 8;       \
  }

POPCOUNT_DEFINE_PORTABLE(I32_POPCNT, u32)

#undef POPCOUNT_DEFINE_PORTABLE

#else

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I32_POPCNT(x) (__builtin_popcount(x))

#endif

#define DIV_S(ut, min, x, y)                                  \
  ((UNLIKELY((y) == 0))                  ? TRAP(DIV_BY_ZERO)  \
   : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
                                         : (ut)((x) / (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x)op(y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                             \
  ((UNLIKELY((x) != (x)))                        ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                 : (ut)(st)(x))

#define I32_TRUNC_S_F64(x) \
  TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))         ? 0                           \
   : (UNLIKELY(!((x)minop(min)))) ? smin                        \
   : (UNLIKELY(!((x) < (max))))   ? smax                        \
                                  : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F64(x)                                        \
  TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., \
              INT32_MAX, x)

static double quiet_nan(double x) {
  uint64_t tmp;
  wasm_rt_memcpy(&tmp, &x, 8);
  tmp |= 0x7ff8000000000000llu;
  wasm_rt_memcpy(&x, &tmp, 8);
  return x;
}

static double wasm_sqrt(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }

#if __has_builtin(__builtin_elementwise_sqrt)
  // Fastest option: doesn't set errno
  return __builtin_elementwise_sqrt(x);
#elif __has_builtin(__builtin_sqrt)
  // Optimized if -fno-math-errno is set
  return __builtin_sqrt(x);
#else
  // Libc call. May/may not be optimized
  return sqrt(x);
#endif
}

static void w2c_basics_f0(w2c_basics*);
static u32 w2c_basics_add_0(w2c_basics*, u32, u32);
static u32 w2c_basics_sum3_0(w2c_basics*, u32, u32, u32);
static u32 w2c_basics_f3(w2c_basics*, u32, u32);
static u32 w2c_basics_f4(w2c_basics*, u32, u32);
static u32 w2c_basics_f5(w2c_basics*, u32, u32);
static u32 w2c_basics_f6(w2c_basics*, u32);
static u32 w2c_basics_f7(w2c_basics*, u32);
static f64 w2c_basics_f8(w2c_basics*, f64, f64);
static f64 w2c_basics_hypot_0(w2c_basics*, f64, f64);
static f64 w2c_basics_f10(w2c_basics*, u32);
static u32 w2c_basics_f11(w2c_basics*, f64);
static u32 w2c_basics_f12(w2c_basics*, f64);
static u32 w2c_basics_f13(w2c_basics*, u64);
static u64 w2c_basics_f14(w2c_basics*, u32);
static u32 w2c_basics_popcount_0(w2c_basics*, u32);
static u32 w2c_basics_f16(w2c_basics*, u32);
static u32 w2c_basics_f17(w2c_basics*, u32, u32);
static u32 w2c_basics_f18(w2c_basics*, u32, u32);
static u32 w2c_basics_triple_0(w2c_basics*, u32);
static void w2c_basics_f20(w2c_basics*);

/* export: 'add' */
u32 w2c_basics_add(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  u32 ret = w2c_basics_add_0(instance, var_p0, var_p1);
  return ret;
}

/* export: 'sum3' */
u32 w2c_basics_sum3(w2c_basics* instance, u32 var_p0, u32 var_p1, u32 var_p2) {
  u32 ret = w2c_basics_sum3_0(instance, var_p0, var_p1, var_p2);
  return ret;
}

/* export: 'hypot' */
f64 w2c_basics_hypot(w2c_basics* instance, f64 var_p0, f64 var_p1) {
  f64 ret = w2c_basics_hypot_0(instance, var_p0, var_p1);
  return ret;
}

/* export: 'popcount' */
u32 w2c_basics_popcount(w2c_basics* instance, u32 var_p0) {
  u32 ret = w2c_basics_popcount_0(instance, var_p0);
  return ret;
}

/* export: 'triple' */
u32 w2c_basics_triple(w2c_basics* instance, u32 var_p0) {
  u32 ret = w2c_basics_triple_0(instance, var_p0);
  return ret;
}

void wasm2c_basics_instantiate(w2c_basics* instance) {
  assert(wasm_rt_is_initialized());
  w2c_basics_f20(instance);
}

void wasm2c_basics_free(w2c_basics* instance) {
}

void w2c_basics_f0(w2c_basics* instance) {
  FUNC_PROLOGUE;
  FUNC_EPILOGUE;
}

u32 w2c_basics_add_0(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 += var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_sum3_0(w2c_basics* instance, u32 var_p0, u32 var_p1, u32 var_p2) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 += var_i1;
  var_i1 = var_p2;
  var_i0 += var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f3(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = var_p0;
  var_i0 *= var_i1;
  var_l2 = var_i0;
  var_i0 = var_p1;
  var_i1 = var_p1;
  var_i0 *= var_i1;
  var_l3 = var_i0;
  var_i0 = var_l2;
  var_i1 = var_l3;
  var_i0 += var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f4(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 = I32_DIV_S(var_i0, var_i1);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f5(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 = DIV_U(var_i0, var_i1);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f6(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 0u;
  var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f7(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = var_p0;
  var_i0 = !(var_i0);
  FUNC_EPILOGUE;
  return var_i0;
}

f64 w2c_basics_f8(w2c_basics* instance, f64 var_p0, f64 var_p1) {
  FUNC_PROLOGUE;
  f64 var_d0, var_d1;
  var_d0 = var_p0;
  var_d1 = var_p1;
  var_d0 += var_d1;
  var_d1 = 2.0;
  var_d0 /= var_d1;
  FUNC_EPILOGUE;
  return var_d0;
}

f64 w2c_basics_hypot_0(w2c_basics* instance, f64 var_p0, f64 var_p1) {
  FUNC_PROLOGUE;
  f64 var_d0, var_d1, var_d2;
  var_d0 = var_p0;
  var_d1 = var_p0;
  var_d0 *= var_d1;
  var_d1 = var_p1;
  var_d2 = var_p1;
  var_d1 *= var_d2;
  var_d0 += var_d1;
  var_d0 = wasm_sqrt(var_d0);
  FUNC_EPILOGUE;
  return var_d0;
}

f64 w2c_basics_f10(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  f64 var_d0;
  var_i0 = var_p0;
  var_d0 = (f64)(s32)(var_i0);
  FUNC_EPILOGUE;
  return var_d0;
}

u32 w2c_basics_f11(w2c_basics* instance, f64 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  f64 var_d0;
  var_d0 = var_p0;
  var_i0 = I32_TRUNC_S_F64(var_d0);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f12(w2c_basics* instance, f64 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  f64 var_d0;
  var_d0 = var_p0;
  var_i0 = I32_TRUNC_SAT_S_F64(var_d0);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f13(w2c_basics* instance, u64 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  u64 var_j0;
  var_j0 = var_p0;
  var_i0 = (u32)(var_j0);
  FUNC_EPILOGUE;
  return var_i0;
}

u64 w2c_basics_f14(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  u64 var_j0;
  var_i0 = var_p0;
  var_j0 = (u64)(s64)(s32)(var_i0);
  FUNC_EPILOGUE;
  return var_j0;
}

u32 w2c_basics_popcount_0(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = var_p0;
  var_i0 = I32_POPCNT(var_i0);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f16(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = var_p0;
  var_i0 = I32_CLZ(var_i0);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f17(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 = I32_ROTL(var_i0, var_i1);
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_f18(w2c_basics* instance, u32 var_p0, u32 var_p1) {
  FUNC_PROLOGUE;
  u32 var_i0;
  var_i0 = var_p0;
  var_i0 = var_p1;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_basics_triple_0(w2c_basics* instance, u32 var_p0) {
  FUNC_PROLOGUE;
  u32 var_i0, var_i1;
  var_i0 = var_p0;
  var_i1 = 3u;
  var_i0 *= var_i1;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_basics_f20(w2c_basics* instance) {
  FUNC_PROLOGUE;
  FUNC_EPILOGUE;
}
