/* Automatically generated by wasm2c, trimmed */
#ifndef BASICS_H_GENERATED_
#define BASICS_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_basics {
  char dummy_member;
} w2c_basics;

void wasm2c_basics_instantiate(w2c_basics*);
void wasm2c_basics_free(w2c_basics*);

/* export: 'add' */
u32 w2c_basics_add(w2c_basics*, u32, u32);

/* export: 'sum3' */
u32 w2c_basics_sum3(w2c_basics*, u32, u32, u32);

/* export: 'hypot' */
f64 w2c_basics_hypot(w2c_basics*, f64, f64);

/* export: 'popcount' */
u32 w2c_basics_popcount(w2c_basics*, u32);

/* export: 'triple' */
u32 w2c_basics_triple(w2c_basics*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* BASICS_H_GENERATED_ */
